# Manipulation de base

## Excercice 1

In [22]:
import numpy as np
A = np.arange(0,100,3)
print(A)

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]


In [23]:
B= np.sin((np.multiply(A,A))*((np.pi)/2))
print(B)
type(B)

[ 0.00000000e+00  1.00000000e+00 -2.20436424e-15  1.00000000e+00
 -8.81745695e-15  1.00000000e+00 -4.11555602e-14  1.00000000e+00
 -3.52698278e-14  1.00000000e+00 -7.64253880e-14  1.00000000e+00
 -1.64622241e-13  1.00000000e+00 -1.86173549e-13  1.00000000e+00
 -1.41079311e-13  1.00000000e+00 -4.84086880e-13  1.00000000e+00
 -3.05701552e-13  1.00000000e+00 -6.06706795e-14  1.00000000e+00
 -6.58488964e-13  1.00000000e+00 -1.18966170e-12  1.00000000e+00
 -7.44694194e-13  1.00000000e+00 -1.14257584e-12  1.00000000e+00
 -5.64317245e-13  1.00000000e+00]


numpy.ndarray

In [24]:
#c= np.max(B)
#print(c)
B.max()

#C = B.max(axis = 0)
#print(C)
#B == 1 #SOLUTION 1
#sum(B == C)

1.0

In [25]:
len(B[B==B.max()])

17

In [26]:
c= np.argwhere(B==B.max())
len(c)

17

In [27]:
d= np.size(c)
d

17

## Excercice 2

In [28]:
A=[[6,2,3,5],[4,6,2,6],[1,3,6,7],[3,6,3,8]]
Z=[[6,2,3,5],[4,6,2,6],[1,3,6,7],[3,6,3,8]]

#print(A)
B=np.triu(Z)
print(Z)
print("\n")
C=np.tril(B)
print(C)
print("\n")
D= (A==C).all()
print(D)

M= np.eye(10)
def est_diagonal(M):
      return True if (M == np.triu(np.tril(M))).all() else False
print("\n")
def est_triangulaire_sup(M):
     return (M == np.tril(M)).all()
    
def est_triangulaire_inf(M):
     return  (M == np.triu(M)).all()  
  
    

print(est_diagonal(M))
print("\n")
print(est_triangulaire_sup(M))


[[6, 2, 3, 5], [4, 6, 2, 6], [1, 3, 6, 7], [3, 6, 3, 8]]


[[6 0 0 0]
 [0 6 0 0]
 [0 0 6 0]
 [0 0 0 8]]


False


True


True


## Excercice 3

In [29]:
Z = np.ones((8,8))
Z[0:-1,1:-1] = 0
print(Z)

[[1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [30]:
A= [[1, 0, 0, 0, 0, 0, 0, 1],[1, 0, 0, 0, 0, 0, 0, 1],[1, 0, 0, 0, 0, 0, 0, 1], [1, 0, 0, 0, 0, 0, 0, 1]]
B=[[1, 0, 0, 0, 0, 0, 0, 1],[1, 0, 0, 0, 0, 0, 0, 1],[1, 0, 0, 0, 0, 0, 0, 1],[1, 1, 1, 1, 1, 1, 1, 1]]
np.concatenate((A, B), axis=0) 
 
 
 
 


array([[1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [31]:
N = []
for x in range(0, 8):
    N.append([0] * 8)
    for y in range (0,8):
        if x >= 7 or y == 0 or y == 7:
            N[x][y] = 1
N

[[1, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 1],
 [1, 1, 1, 1, 1, 1, 1, 1]]

## Excercice 4

In [32]:
import time 
tmps1=time.time()
list =range(1000001)
sum(list)
tmps2=time.time()-tmps1
print(sum(list))
print( "Temps d'execution = %f" %tmps2)

500000500000
Temps d'execution = 0.060968


In [33]:
A = np.arange(0,10000001)
print(np.sum(A,dtype=np.int64))

50000005000000


In [34]:
import time 
tmps1=time.time()
A = np.arange(0,10000001)
print(np.sum(A,dtype=np.int64))
tmps2=time.time()-tmps1
print( "Temps d'execution = %f" %tmps2)

50000005000000
Temps d'execution = 0.053977


## Excercice 5

In [46]:
A = np.random.randint(100, size=(50, 50))
A

array([[60, 37, 65, ..., 91, 94, 20],
       [62, 77, 94, ..., 62, 51, 18],
       [19, 46,  6, ..., 11,  2, 67],
       ...,
       [22, 97, 89, ..., 32, 71, 20],
       [38, 81, 28, ..., 99, 89, 68],
       [18, 58, 39, ...,  6,  2,  1]])

In [47]:
max = 0
for i in range(49):
    for j in range(49):
        if max < A[j+1][i]-A[i][j]:
            max = A[i][j]
print(max)()

94


## Excercice 6

In [37]:
import numpy as np
a = np.random.rand(50,50)
print(a)
print("\n")
count=np.count_nonzero(a<=0.5)
print(count)

b=(a>0.5).astype(int)
print(b)

print("\n")

c=np.select(a<=0.5, a)
np.ceil(c)
d=np.select(a>0.5, a)
np.floor(d)
print(np.ceil(c))
print(np.floor(d))
print("\n")

d= np.where(a<0.5, 0,1)
print(d)

[[0.38124232 0.23400411 0.87813991 ... 0.26663648 0.56500417 0.51089156]
 [0.32028149 0.29247927 0.98332083 ... 0.92850825 0.0505661  0.91969708]
 [0.53052674 0.51793717 0.51227638 ... 0.45077121 0.95470188 0.80461935]
 ...
 [0.14048553 0.85916181 0.8904688  ... 0.72998734 0.66429496 0.94024542]
 [0.17999286 0.78453125 0.39352235 ... 0.06880263 0.84385641 0.29312151]
 [0.6166651  0.63156612 0.57451444 ... 0.81202186 0.33500703 0.18372947]]


1232
[[0 0 1 ... 0 1 1]
 [0 0 1 ... 1 0 1]
 [1 1 1 ... 0 1 1]
 ...
 [0 1 1 ... 1 1 1]
 [0 1 0 ... 0 1 0]
 [1 1 1 ... 1 0 0]]


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]


[[0 0 1 ... 0 1 1]
 [0 0 1 ... 1 0 1]
 [1 1 1 ... 0 1 1]
 ...
 [0 1 1 ... 1 1 1]
 [0 1 0 ... 0 1 0]
 [1 1 1 ... 1 0 0

## Exercice 7

In [38]:
a= np.array([[1,2,1,1],[0,1,2,1],[1,0,1,2],[2,1,0,1]]) 
b=np.array([0,0,1,0])
x = np.linalg.solve(a, b)
print(x)


[-0.5  0.  -0.5  1. ]


## Excercice 8

In [39]:
text=input("Please enter the string to encode")
encoded=[]
index=0
amount=1
while index<=(len(text)-1):  
  if index==(len(text)-1) or text[index]!=text[(index+1)]:
    encoded.append((text[index],amount))        
    amount=1
  else:
    amount=amount+1            
  index=index+1   
print(encoded)

Please enter the string to encode
[]


In [41]:
def encode(input_string):
    count = 1
    prev = ''
    lst = []
    for character in input_string:
        if character != prev:
            if prev:
                entry = (prev,count)
                lst.append(entry)
                #print lst
            count = 1
            prev = character
        else:
            count += 1
    else:
        try:
            entry = (character,count)
            lst.append(entry)
            return (lst, 0)
        except Exception as e:
            print("Exception encountered {e}".format(e=e)) 
            return (e, 1)
 
def decode(lst):
    q = ""
    for character, count in lst:
        q += character * count
    return q
 
#Method call
value = encode(input("Please enter the string to encode  "))
if value[1] == 0:
    print("Encoded value is {}".format(value[0]))
    decode(value[0])
    print(decode(value[0]))

Please enter the string to encode  GGGGFSSSSSLLLLOOO
Encoded value is [('G', 4), ('F', 1), ('S', 5), ('L', 4), ('O', 3)]
GGGGFSSSSSLLLLOOO
